#!/bin/bash

usage() {
  echo "Show synonyms and antonyms of the word from thesaurus.com"
  echo "Usage:"
  echo "    snm <word>  - show synonym and antonym list"
  echo "    snm         - show word origin of the last retrieved entry"
  exit 0
}

columnize() {
  f1=$1
  width=$2
  awk '{printf "%-'$width's\n", $0}' $f1
  for i in {1..50}; do
    printf "%-${width}s\n"
  done
}

urlencode() {
  echo "$1" | sed 's/ /%20/g' | sed "s/'/%27/g"
}

if [ $# -eq 1 ] && [ "$1" = "-h" ]; then
  usage
fi

if [ $# -eq 0 ]; then
  last=`ls -tr $HOME/.snm | tail -n 1`
  if [ -n "$last" ]; then
    w3m -dump -cols 180 "$HOME/.snm/$last/page.htm" | grep -A 1000 "Word Origin" | grep -B 1000 "EXPAND" | head -n -2 
  fi
  exit 0
fi

word="$*"
mkdir -p $HOME/.snm

# if the word was already processed (in dir cache)
if ! mkdir "$HOME/.snm/$word" > /dev/null 2>&1; then
  cat "$HOME/.snm/$word/final"
  touch "$HOME/.snm/$word"
  exit 0
fi


cd "$HOME/.snm/$word"
curl -s http://www.thesaurus.com/browse/`urlencode $word` > page.htm

# split multiple tabs, you need to ignore tab00
csplit -f tab page.htm '/synonym-description/' {*} > /dev/null
  
rm tab00

[ -e tab01 ] || { echo "Not found"; exit 2; }
  
for tab in tab??; do
  # split tabs into synonym - antonym sections
  csplit -f $tab $tab '/container-info antonyms/' {*} > /dev/null
  # ensure that at least 2 chunk files exist - necessary for further processing
  touch ${tab}00
  touch ${tab}01
done

rm -f syn_*; rm -f ant_*

W1=30
W2=$((W1+1))
W3=$((W2*2))

for tab in tab??; do
  #printf "\nMeaning:\n" > p$tab
  printf "@\n@\n" > ${tab}_sa
  grep '<strong class="ttl">\w' ${tab}00 | sed 's/.*">\(.*\)<.*/\1/g' >> ${tab}_sa      # extract meaning/tab title
  echo '-------------------------------' >> ${tab}_sa

  printf "@\n%-${W2}s%-${W2}s\n@\n" "Synonyms:" "Antonyms:" >> ${tab}_sa
  grep relevant-[123] ${tab}00 | grep -o 'thesaurus\.com\/browse\/\S*' | sed 's/%20/ /g' | sed "s/%27/'/g" | sed 's/thesaurus.com\/browse\/\(.*\)"/\1/g' >> ${tab}_syn
  grep relevant--[123] ${tab}01 | grep -o 'thesaurus\.com\/browse\/\S*' | sed 's/%20/ /g' | sed "s/%27/'/g" | sed 's/thesaurus.com\/browse\/\(.*\)"/\1/g' >> ${tab}_ant

  columnize ${tab}_syn $W1 > ${tab}_syn_col
  columnize ${tab}_ant $W1 > ${tab}_ant_col

  paste -d' ' ${tab}_syn_col ${tab}_ant_col >> ${tab}_sa
  columnize ${tab}_sa $W3 > ${tab}_sa_col
done

echo tab*_sa_col | xargs -n 3 paste -d' ' | sed '/^\s*$/d' > tab_all

cat tab_all | sed 's/@/ /g' > final

rm tab*

cat final

